### ISSUE TITLE
Passwords are stored without encryption.

### ISSUE THREAD

**Issue by rohandebsarkar** [ankitjosh78/PassBot#1]
I was checking out the code, while I found that you are storing the passwords without encryption. This is very dangerous. Passwords should never be stored without encryption as it is equivalent to writing passwords in a notebook with plain text.

**Comment by ankitjosh78** [comment]
> I was checking out the code, while I found that you are storing the passwords without encryption. This is very dangerous. Passwords should never be stored without encryption as it is equivalent to writing passwords in a notebook with plain text.

Yeah,you are right. Its not yet complete bro. I was planning to encrypt that text file with some form of a master password. But,thanks for taking interest in this.
